name: Backup to S3

on:
    workflow_dispatch:
    schedule:
        - cron: "0 22 * * *" # at 10pm every day

env:
    SERVER_ID: "32657111668989263"

jobs:
    backup:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install dependencies
              run: |
                  sudo -v ; curl https://rclone.org/install.sh | sudo bash

            - name: Retrieve server hostname
              run: |
                  TS_JSON=$(curl "https://api.tailscale.com/api/v2/device/${{ env.SERVER_ID }}" -u "${{ secrets.TS_KEY }}:")
                  HOSTNAME=$(echo $TS_JSON | jq -r '.name')
                  echo "SERVER_HOSTNAME=$HOSTNAME" >> $GITHUB_ENV

            - name: Connect to Tailscale network
              uses: tailscale/github-action@v2
              with:
                  oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
                  oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
                  tags: tag:ci

            - name: Install SSH key
              run: |
                  install -m 600 -D /dev/null ~/.ssh/id_rsa
                  echo "${{ secrets.CI_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ env.SERVER_HOSTNAME }} > ~/.ssh/known_hosts

            - name: Perform backup
              run: |
                  BACKUP_ARCHIVE_NAME=$(date +backup-%Y-%m-%d-%H-%M-%S.tar.xz)
                  echo "BACKUP_ARCHIVE_NAME=$BACKUP_ARCHIVE_NAME" >> $GITHUB_ENV
                  ssh -t ci@${{ env.SERVER_HOSTNAME }} "sudo tar -cvJSf /$BACKUP_ARCHIVE_NAME \
                    --exclude=/$BACKUP_ARCHIVE_NAME \
                    --exclude=/dev \
                    --exclude=/mnt \
                    --exclude=/proc \
                    --exclude=/sys \
                    --exclude=/tmp \
                    --exclude=/media \
                    --exclude=/lost+found \
                    --exclude /var/lib/docker \
                    /"
                  rsync -chavzP --stats ci@${{ env.SERVER_HOSTNAME }}:/$BACKUP_ARCHIVE_NAME .
                  ssh -t ci@${{ env.SERVER_HOSTNAME }} "rm /$BACKUP_ARCHIVE_NAME"

            - name: Upload backup to S3
              run: |
                  mkdir -p ~/.config/rclone || true

                  echo "[dothq]" > ~/.config/rclone/rclone.conf
                  echo "type = s3" >> ~/.config/rclone/rclone.conf
                  echo "provider = Cloudflare" >> ~/.config/rclone/rclone.conf
                  echo "access_key_id = ${{ secrets.R2_ACCESS_ID }}" >> ~/.config/rclone/rclone.conf
                  echo "secret_access_key = ${{ secrets.R2_SECRET_KEY }}" >> ~/.config/rclone/rclone.conf
                  echo "endpoint = https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com" >> ~/.config/rclone/rclone.conf
                  echo "acl = private" >> ~/.config/rclone/rclone.conf

                  BACKUP_ARCHIVE_PATH=$(date +%Y/%m)
                  rclone copy \
                    -P \
                    --max-age 3d \
                    --s3-upload-cutoff=100M \
                    --s3-chunk-size=100M \
                    $BACKUP_ARCHIVE_NAME \
                    "dothq:${{ secrets.R2_BACKUPS_BUCKET }}/"

            - name: Nuke SSH keys
              run: rm -rf ~/.ssh
