name: Build and maybe deploy to dothq.org

on:
    push:
        branches: ["production", "staging"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Install dependencies
              run: |
                  yarn

            - name: Build
              run: |
                  yarn build

            - name: Test
              if: github.ref == 'refs/heads/production'
              run: |
                  yarn dev &
                  SERVER_PID=$!
                  while ! nc -z localhost 3000; do
                    sleep 0.1
                  done
                  yarn test

    # Staging deployments
    deploy-staging:
        runs-on: ubuntu-latest
        needs: build
        if: github.ref == 'refs/heads/staging'
        environment:
            name: Staging
            url: "http://dothq.local"
        permissions:
            contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Deploy to staging server
              uses: ./.github/actions/run-via-ssh
              with:
                  ts_hostname: ${{ vars.SERVER_HOSTNAME }}
                  ts_oauth_client_id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
                  ts_oauth_secret: ${{ secrets.TS_OAUTH_SECRET }}
                  ts_tags: tag:ci
                  ssh_username: ci
                  ssh_private_key: ${{ secrets.CI_PRIVATE_KEY }}
                  run: |
                      cd /app
                      git reset --hard
                      git pull
                      ./scripts/rebuild_docker.sh

    # Production deployments
    deploy-production:
        runs-on: ubuntu-latest
        needs: build
        if: github.ref == 'refs/heads/production'
        environment:
            name: Production
            url: "https://www.dothq.org"
        permissions:
            contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Deploy to production server
              uses: ./.github/actions/run-via-ssh
              with:
                  ts_hostname: ${{ vars.SERVER_HOSTNAME }}
                  ts_oauth_client_id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
                  ts_oauth_secret: ${{ secrets.TS_OAUTH_SECRET }}
                  ts_tags: tag:ci
                  ssh_username: ci
                  ssh_private_key: ${{ secrets.CI_PRIVATE_KEY }}
                  run: |
                      cd /app
                      git reset --hard
                      git pull
                      ./scripts/rebuild_docker.sh
