name: Generate l10n data

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v1
            - name: Install libretranslate
              run: pip install libretranslate
