name: Renew production certificates

on:
    workflow_dispatch:
    schedule:
        - cron: "0 5 * * *" # every day at 5am

jobs:
    renew:
        runs-on: ubuntu-latest
        environment:
            name: Production
        permissions:
            contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Renew production certificates
              uses: ./.github/actions/run-via-ssh
              with:
                  ts_hostname: ${{ vars.SERVER_HOSTNAME }}
                  ts_oauth_client_id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
                  ts_oauth_secret: ${{ secrets.TS_OAUTH_SECRET }}
                  ts_tags: tag:ci
                  ssh_username: ci
                  ssh_private_key: ${{ secrets.CI_PRIVATE_KEY }}
                  run: |
                      cd /app
                      ./scripts/renew_certificates_docker.sh
